In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("Countries.csv")
df = pd.DataFrame(data)
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [5]:
#which country has the highest population

In [16]:
df.columns.sort_values(ascending=True)

Index(['agricultural_land', 'alternative_nuclear_energy_pct', 'armed_forces',
       'birth_rate', 'capital_city', 'central_government_debt_pct_gdp',
       'co2_emissions', 'continent', 'country', 'country_long', 'currency',
       'death_rate', 'democracy_score', 'democracy_type', 'demonym',
       'electricity_access_pct', 'electricty_production_coal_pct',
       'electricty_production_gas_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_nuclear_pct', 'electricty_production_oil_pct',
       'electricty_production_renewable_pct', 'energy_imports_pct',
       'expense_pct_gdp', 'fertility_rate', 'forest_area',
       'fossil_energy_consumption_pct', 'gdp', 'greenhouse_other_emissions',
       'health_expenditure_capita', 'health_expenditure_pct_gdp',
       'hiv_incidence', 'hospital_beds', 'inflation',
       'internally_displaced_persons', 'internet_pct', 'land_area', 'latitude',
       'life_expectancy', 'longitude', 'median_age', 'methane_emissions',
       'military_expenditure_pct_gdp', 'net_migration',
       'nitrous_oxide_emissions', 'political_leader', 'population',
       'population_female', 'population_male', 'press', 'region',
       'renewable_energy_consumption_pct', 'rural_land', 'rural_population',
       'self_employed_pct', 'suicide_rate', 'tax_revenue_pct_gdp', 'title',
       'unemployment_pct', 'urban_land', 'urban_population',
       'urban_population_under_5m', 'vulnerable_employment_pct',
       'women_parliament_seats_pct'],
      dtype='str')

In [22]:
df[df['population'] == df['population'].max()][["country",'population']]

   country  population
75   India  1417173173

In [6]:
#which country has the lowest population

In [21]:
df[df['population'] == df['population'].min()][["country",'population']]

    country  population
179  Tuvalu       11312

In [7]:
#what is the capital of the country which have the least pooulation

In [23]:
df[df['population'] == df['population'].min()][["country",'capital_city']]

    country capital_city
179  Tuvalu     Funafuti

In [8]:
#give me the top 5 countries with the highest democratic score

In [32]:
df.sort_values(by = 'democracy_score', ascending= False)[['country','democracy_score']].head()

         country  democracy_score
127       Norway             9.87
74       Iceland             9.58
164       Sweden             9.39
122  New Zealand             9.26
46       Denmark             9.22

In [9]:
#how many total regions are there

In [47]:
df['region'].value_counts()

region
Western Asia                 17
Eastern Africa               17
Western Africa               16
Southern Europe              15
Caribbean                    13
South America                12
South-Eastern Asia           11
Middle Africa                10
Eastern Europe               10
Northern Europe              10
Southern Asia                 9
Western Europe                9
Central America               8
Northern Africa               6
Southern Africa               5
Eastern Asia                  5
Central Asia                  5
Micronesia                    5
Melanesia                     4
Polynesia                     3
Australia and New Zealand     2
Northern America              2
Name: count, dtype: int64

In [46]:
df['region'].value_counts().count()

np.int64(22)

In [10]:
#how many countries lies in the Eastern Europe region

In [41]:
df[df['region']=='Eastern Europe']['country'].count()

np.int64(10)

In [11]:
#who is the political leader of the 2nd highest population country

In [55]:
df[df['population'] == df['population'].nlargest(2).iloc[1]]["political_leader"]

34    Xi Jinping
Name: political_leader, dtype: str

In [12]:
#how many countries are there whose political leaders are unknoun

In [59]:
df[df['political_leader'].isna()]['country']

27                         Cabo Verde
151                   Slovak Republic
159               St. Kitts and Nevis
160                         St. Lucia
161    St. Vincent and the Grenadines
172                       Timor-Leste
190                West Bank and Gaza
Name: country, dtype: str

In [13]:
#how many countries have republic in their name

In [76]:
df[df['country_long'].str.contains("republic", case= False)]['country'].count()

np.int64(125)

In [14]:
#which country in africa region have the highest population

In [95]:
df1 = df[df['continent']=='Africa']
df1[df1['population'] == df1['population'].max()][['country','population']]

     country  population
125  Nigeria   218541212

In [99]:
df[df['country'] == 'India']['democracy_score']

75    7.23
Name: democracy_score, dtype: float64

In [100]:
#find the total pooulation of entire world

In [133]:
total_population = df['population'].sum()
print("The total population in the world is:",total_population)

The total population in the world is: 7913042291

In [101]:
#what is the  average and middle age across all the coountries

In [139]:
print('The average age of the world population is:',df['life_expectancy'].mean())
print("The median age of the world population is:",df['median_age'].mean().round(2))

The average age of the world population is: 71.0
The median age of the world population is: 25.66

In [103]:
#find which currency is utilized by the highest number of countries

In [ ]:
most_common_currnecy = df['currency'].mode()[0]
print('The most used currency in the world is:',most_common_currnecy)

The most used currency in the world is: Euro

In [104]:
#group the data by democracy_type and calculate the average democracy_score

In [170]:
democracy_type_set = df['democracy_type'].value_counts()
print('The group of the countries based on democracy type is as:',democracy_type_set)
print('\n The average democracy score of all  the countries in the world is:',df['democracy_score'].mean().round(2))

The group of the countries based on democracy type is as: democracy_type
Authoritarian       53
Flawed democracy    53
Hybrid regime       39
Unknown             29
Full democracy      20
Name: count, dtype: int64

 The average democracy score of all  the countries in the world is: 4.64

In [171]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    str
 1   country_long                             194 non-null    str
 2   currency                                 194 non-null    str
 3   capital_city                             194 non-null    str
 4   region                                   194 non-null    str
 5   continent                                194 non-null    str
 6   demonym                                  194 non-null    str
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    str
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    str
 63  title                                    187 non-null    str
dtypes: float64(48), int64(6), str(10)
memory usage: 97.1 KB

In [172]:
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [105]:
#find all the countries where women hold more than 40% parliament seats

In [181]:
df[df['women_parliament_seats_pct']>40][['country','women_parliament_seats_pct']].sort_values(by='women_parliament_seats_pct',ascending=True)

                  country  women_parliament_seats_pct
111               Moldova                     40.5941
121           Netherlands                     40.6667
9                 Austria                     40.9836
57               Ethiopia                     41.4894
165           Switzerland                     41.5000
126       North Macedonia                     41.6667
116            Mozambique                     42.4000
15                Belgium                     42.6667
157                 Spain                     42.9799
46                Denmark                     43.5754
118               Namibia                     44.2308
146               Senegal                     44.2424
6               Argentina                     44.7471
127                Norway                     44.9704
59                Finland                     45.5000
19                Bolivia                     46.1538
164                Sweden                     46.4183
3                 Andorra                     46.4286
155          South Africa                     46.5000
38             Costa Rica                     47.3684
74                Iceland                     47.6190
109                Mexico                     50.0000
182  United Arab Emirates                     50.0000
122           New Zealand                     50.4202
123             Nicaragua                     51.6483
41                   Cuba                     53.4130
141                Rwanda                     61.2500

In [106]:
#find the countries which has the highest positive net migration and negative net migration

In [192]:
pos_migration = df[df['net_migration'] == df['net_migration'].max()][['country','net_migration']]
print('The highest migration rate country is:')
pos_migration

The highest migration rate country is:

           country  net_migration
184  United States         561580

In [193]:
neg_migration = df[df['net_migration'] == df['net_migration'].min()][['country','net_migration']]
print('The lowest migration rate country is:')
neg_migration

The lowest migration rate country is:

       country  net_migration
188  Venezuela        -525116

In [107]:
#find how many contries have a political leader whose title contains the word "king","Sultan" or "Emir"

In [208]:
lst1 = ['king','Sultan','Emir']
pattern = "|".join(lst1)
df[df['title'].str.contains(pattern, case = False)][['country','title']]

          country                      title
11        Bahrain                       King
23         Brunei  Sultan and Prime Minister
56       Eswatini                       King
84         Jordan                       King
89         Kuwait                       Emir
115       Morocco                       King
128          Oman  Sultan and Prime Minister
138         Qatar                       Emir
145  Saudi Arabia                       King

In [203]:
df['title']

0                                     President
1                                Prime Minister
2                                     President
3                            Head of Government
4                                     President
                         ...
189    General Secretary of the Communist Party
190                                         NaN
191                                   President
192                                   President
193                                   President
Name: title, Length: 194, dtype: str

In [108]:
#make a new column which contain the population_density for each country

In [218]:
df['population_density']=df['population']/ df['land_area']
df[['country','population_density']].sort_values(by='population_density', ascending = False).round(4)

       country  population_density
112     Monaco          17991.6132
150  Singapore           7851.0056
11     Bahrain           1875.4561
103   Maldives           1745.9567
105      Malta           1635.6781
..         ...                 ...
96       Libya              3.8717
74     Iceland              3.7876
8    Australia              3.3774
118    Namibia              3.1180
113   Mongolia              2.1819

[194 rows x 2 columns]

In [109]:
#find which country in the Europe continent has the highest unemployment rate and check what is its democracy_type

In [221]:
europe_cont = df[df['continent'] == 'Europe']
europe_cont[europe_cont['unemployment_pct'] == europe_cont['unemployment_pct'].max()][['country','unemployment_pct']]

        country  unemployment_pct
114  Montenegro            15.402

In [220]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title',
       'population_density'],
      dtype='str')

In [110]:
#Find all countries that produce more than 50% of their electricity from hydro-electric sources but still have a fossil energy consumption rate above 30%.

In [234]:
df[(df['electricty_production_hydroelectric_pct']>50) & (df['fossil_energy_consumption_pct']>30)][["country","electricty_production_hydroelectric_pct",'fossil_energy_consumption_pct']]

,country,electricty_production_hydroelectric_pct,fossil_energy_consumption_pct
1,Albania,100.0000,61.4218
4,Angola,53.1749,48.3056
9,Austria,59.9971,65.6618
22,Brazil,61.8485,59.1075
29,Cameroon,74.9926,38.3179
30,Canada,56.7442,74.0891
35,Colombia,64.9594,76.6857
37,Congo,53.3449,40.4806
38,Costa Rica,74.6115,49.8803
40,Croatia,56.8695,70.7037
44,Dem. People's Rep. Korea,72.7961,62.0520
50,Ecuador,50.7007,86.8847
62,Georgia,78.0393,72.2095
64,Ghana,50.8659,52.5431
90,Kyrgyz Republic,85.1880,75.4762
117,Myanmar,58.8541,44.2899
118,Namibia,97.7865,66.7191
122,New Zealand,55.5028,59.7492
127,Norway,95.8255,56.9516
131,Panama,60.7712,80.7127
133,Paraguay,99.9982,33.7033
162,Sudan,64.5359,31.7265
163,Suriname,60.0531,76.2535
165,Switzerland,57.8816,50.1682
167,Tajikistan,98.4734,45.9841
185,Uruguay,60.1601,46.2703
188,Venezuela,63.6950,88.3780

In [111]:
#find what is the life_expectancy in the Africa's top 3 countries richest countries by gdp

In [227]:
africa_cont = df[df['continent']=='Africa']
africa_cont.sort_values(by = 'gdp',ascending = False)[['country','gdp','life_expectancy']].head(3)

          country           gdp  life_expectancy
125       Nigeria  4.773860e+11             53.0
51          Egypt  4.767480e+11             70.0
155  South Africa  4.058700e+11             62.0